# Generated by Django 6.0.6 on 2026-06-21 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kelas',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='MateriUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='materi/%Y/%m/')),
                ('diupload_pada', models.DateTimeField(auto_now_add=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi_list', to='dashboard.kelas')),
            ],
            options={
                'verbose_name_plural': 'Materi Upload',
                'ordering': ['-diupload_pada'],
            },
        ),
        migrations.CreateModel(
            name='ProfilGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapaan', models.CharField(default='Bu', max_length=50)),
                ('sekolah', models.CharField(blank=True, max_length=150)),
                ('notifikasi_email', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nilai_matematika', models.FloatField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nilai_bahasa', models.FloatField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kehadiran_persen', models.FloatField(default=90, help_text='Persentase kehadiran siswa', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('keaktifan', models.FloatField(default=70, help_text='Skor keaktifan di kelas (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nomor_meja', models.PositiveIntegerField(default=1)),
                ('cluster_label', models.CharField(blank=True, choices=[('cerdas', 'Cerdas'), ('pintar', 'Pintar'), ('malas', 'Malas')], max_length=10, null=True)),
                ('cluster_terakhir_diupdate', models.DateTimeField(blank=True, null=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_list', to='dashboard.kelas')),
            ],
            options={
                'verbose_name_plural': 'Siswa',
                'ordering': ['nomor_meja', 'nama'],
            },
        ),
    ]
