# Generated by Django 6.0.6 on 2026-06-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='alpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='eksakta',
            field=models.FloatField(blank=True, help_text='Rata-rata nilai eksakta (Matematika)', null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='izin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nis',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nonekstakta',
            field=models.FloatField(blank=True, help_text='Rata-rata nilai non-eksakta', null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='rangking',
            field=models.FloatField(blank=True, help_text='Rangking di dalam kelasnya', null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='sakit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='skor_akademik',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='skor_disiplin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
