# Generated by Django 6.0.6 on 2026-06-22 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profilguru_gelar_walikelas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatUploadXlsx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255)),
                ('jumlah_siswa', models.PositiveIntegerField(default=0)),
                ('diupload_pada', models.DateTimeField(auto_now_add=True)),
                ('diupload_oleh', models.ForeignKey(blank=True, help_text='User yang melakukan upload (bisa guru pemilik kelas atau superuser).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_upload_xlsx', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_upload', to='dashboard.kelas')),
            ],
            options={
                'verbose_name': 'Riwayat Upload Xlsx',
                'verbose_name_plural': 'Riwayat Upload Xlsx',
                'ordering': ['-diupload_pada'],
            },
        ),
    ]
