# Generated by Django 5.2.15 on 2026-07-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_riwayatuploadxlsx'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatuploadxlsx',
            name='file_asli',
            field=models.FileField(blank=True, help_text='Salinan file Excel asli yang diupload, dipakai untuk diunduh kembali.', null=True, upload_to='riwayat_upload_xlsx/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='jumlah_ekstrakurikuler',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah kegiatan ekstrakurikuler yang diikuti siswa'),
        ),
    ]
