# Generated by Django 5.2.15 on 2026-07-23 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_riwayatuploadxlsx_file_asli_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPerbangku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_meja', models.PositiveIntegerField(default=0)),
                ('jumlah_siswa', models.PositiveIntegerField(default=0)),
                ('diatur_pada', models.DateTimeField(auto_now_add=True)),
                ('diatur_oleh', models.ForeignKey(blank=True, help_text='User yang menjalankan pengaturan ulang posisi meja.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_perbangku', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_perbangku', to='dashboard.kelas')),
            ],
            options={
                'verbose_name': 'Riwayat Perbangku',
                'verbose_name_plural': 'Riwayat Perbangku',
                'ordering': ['-diatur_pada'],
            },
        ),
    ]
