# Generated by Django 5.2.15 on 2026-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_riwayatperbangku'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatperbangku',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Salinan susunan meja & data siswa saat itu, dipakai untuk preview/unduh riwayat.'),
        ),
    ]
