# Generated by Django 5.2.15 on 2026-07-23 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_riwayatperbangku_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatClusterKmeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_kelas', models.CharField(blank=True, default='', help_text="Judul gabungan kelas setingkat saat itu, mis. 'Kelas 1A dan 1B'.", max_length=150)),
                ('jumlah_siswa', models.PositiveIntegerField(default=0)),
                ('jumlah_cerdas', models.PositiveIntegerField(default=0)),
                ('jumlah_pintar', models.PositiveIntegerField(default=0)),
                ('jumlah_malas', models.PositiveIntegerField(default=0)),
                ('sumber', models.CharField(choices=[('manual', 'Jalankan Ulang Manual'), ('upload_excel', 'Upload Excel')], default='manual', max_length=20)),
                ('dijalankan_pada', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Salinan hasil clustering per siswa saat itu, dipakai untuk preview/unduh riwayat.')),
                ('dijalankan_oleh', models.ForeignKey(blank=True, help_text='User yang menjalankan clustering (guru pemilik kelas atau superuser).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_cluster_kmeans', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_cluster', to='dashboard.kelas')),
            ],
            options={
                'verbose_name': 'Riwayat Cluster K-Means',
                'verbose_name_plural': 'Riwayat Cluster K-Means',
                'ordering': ['-dijalankan_pada'],
            },
        ),
    ]
